import { Champion } from './champion';

const baseImgUrl = '/assets/champions/';
const baseHP = 10;
const baseAttack = 5;
const baseDefence = 2;

export const CHAMPIONS: Champion[] = [
  {
    pantheon: 'Egyptian',
    name: 'Anubis',
    avatar: baseImgUrl + 'anubis.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Egyptian',
    name: 'Apophis',
    avatar: baseImgUrl + 'apophis.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Egyptian',
    name: 'Hathor',
    avatar: baseImgUrl + 'hathor.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Egyptian',
    name: 'Isis',
    avatar: baseImgUrl + 'isis.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Egyptian',
    name: 'Ra',
    avatar: baseImgUrl + 'ra.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Egyptian',
    name: 'Shakti',
    avatar: baseImgUrl + 'shakti.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },

  {
    pantheon: 'Greek',
    name: 'Ares',
    avatar: baseImgUrl + 'ares.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Greek',
    name: 'Posejdon',
    avatar: baseImgUrl + 'posejdon.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Greek',
    name: 'Artemis',
    avatar: baseImgUrl + 'artemis.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Greek',
    name: 'Athena',
    avatar: baseImgUrl + 'athena.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Greek',
    name: 'Hephaestus',
    avatar: baseImgUrl + 'hephaestus.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Greek',
    name: 'Zeus',
    avatar: baseImgUrl + 'zeus.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },

  {
    pantheon: 'Hindu',
    name: 'Ganesha',
    avatar: baseImgUrl + 'ganesha.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Hindu',
    name: 'Rama',
    avatar: baseImgUrl + 'rama.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Hindu',
    name: 'Shakti',
    avatar: baseImgUrl + 'shakti.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Hindu',
    name: 'Shiva',
    avatar: baseImgUrl + 'shiva.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Hindu',
    name: 'Vishnu',
    avatar: baseImgUrl + 'vishnu.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Hindu',
    name: 'Devi',
    avatar: baseImgUrl + 'devi.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },

  {
    pantheon: 'Nordic',
    name: 'Freya',
    avatar: baseImgUrl + 'freya.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Nordic',
    name: 'Hel',
    avatar: baseImgUrl + 'hel.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Nordic',
    name: 'Loki',
    avatar: baseImgUrl + 'loki.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Nordic',
    name: 'Odin',
    avatar: baseImgUrl + 'odin.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Nordic',
    name: 'Thor',
    avatar: baseImgUrl + 'thor.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
  {
    pantheon: 'Nordic',
    name: 'Baldur',
    avatar: baseImgUrl + 'baldur.jpg',
    attack: baseAttack + Math.floor(Math.random() * 3) + 1,
    defence: baseDefence + Math.floor(Math.random() * 3) + 1,
    hp: baseHP + Math.floor(Math.random() * 3) + 1,
  },
];
